name: CI/CD Pipeline to ECR
on:
  push:
    branches:
      - master
      
env:
  docker_image: "666132446347.dkr.ecr.ap-south-1.amazonaws.com/test:latest"
  aws_region: "ap-south-1"   
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (optional but recommended for advanced builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AccessKey }}
        aws-secret-access-key: ${{ secrets.SecretKey }}
        aws-region: ${{env.aws_region}}

    # Step 4: Log in to Amazon ECR
    - name: Login to Amazon ECR
      run: |
       aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 666132446347.dkr.ecr.ap-south-1.amazonaws.com
       
    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{env.docker_image}} .
        
    # Step 6: Push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{env.docker_image}}
      
